version: '3'

services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: togo_db
    ports:
      - 5432:5432 # expose port
    volumes:
    - pgdata_prod:/var/lib/postgresql/data/ # persist data

  togo:
    build: .
    ports:
      - 8888:8888
    restart: always
    environment:
      POSTGRES_DATASOURCE: "host=database port=5432 user=admin password=admin dbname=togo_db sslmode=disable"
      SQLITE_DATASOURCE: "./data.db"
      DIALECT: "postgres"
      JWT_KEY: "wqGyEBBfPK9w3Lxw"
      TOGO_PORT: "8888"
    depends_on:
      - database

volumes:
  pgdata_prod:
